#!/bin/bash
# Start server script
echo "Starting ROSbridge"
gnome-terminal -x roslaunch rosbridge_server rosbridge_websocket.launch
sleep 2 #Give rosbridge 2s to start
echo "Starting Web Server"
gnome-terminal -x node web_server.js
echo "Opening Browser"
python -m webbrowser "http://127.0.0.1:1337"
